FROM drupal:9.4.8-php8.1-apache-buster

# Copy Apache2
COPY volumes/apache/* /etc/apache2/sites-enabled
# RUN "a2ensite /etc/apache2/sites-available/test-domain.conf"
# RUN "service apache2 reload"
# RUN "echo 'Site Added Successfully"

    